[package]
name = "xswezan/superparty"
description = "Create parties (a group of players) with ease!"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"
exclude = [
	"moonwave.toml",
	"foreman.toml",
	"selene.toml",
	".gitignore",
	"README.md",
	"docs",
	".editorconfig"
]

[dependencies]
Janitor = "howmanysmall/janitor@1.14.2"
Promise = "evaera/promise@4.0.0"